#! bin/bash

#:显示(设置)shell变量
set -e

export LC_ALL=zh_CN.GB2312;export LANG=zh_CN.GB2312

if [ -d ~/.VPodsRepertory ]
then
  echo "Already installed VPodsRepertory"
  echo "Update VPodsRepertory..."
  cd ~/.VPodsRepertory
  hash git >/dev/null && /usr/bin/env git pull --verbose|| {
	echo "git not installed"
	exit
  }
else
	echo "Cloning VPodsRepertory..."
	hash git >/dev/null && /usr/bin/env git clone https://github.com/heyuan110/PodsRepertory.git ~/.VPodsRepertory || {
	  echo "git not installed"
	  exit
	}
fi

toPath=~/.cocoapods/repos/master/Specs/
if [ -d "$toPath" ]; then
	echo "${toPath} exists"
else 
	mkdir -p $toPath
	echo "create ${toPath} folder successed!"
fi
echo "Update podspecs..."
cp -rf ~/.VPodsRepertory/Podspecs/* $toPath
ls -l ~/.VPodsRepertory/Podspecs | grep '^d' | awk '{ print $9 }'
# rm -rf ~/.VPodsRepertory
echo "Installed successfully! please have try 'pod search VExtensions' ~_~！"